name: Draft release
on:
  push:
    branches:
      - main

jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions:
      # Required to request the OIDC JWT Token
      id-token: write
      # Required when GH token is used to authenticate with private repo
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Draft release
        uses: KoblerS/release-drafter@v1
